### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by bagusflyer** [victorBaro/PopPlayground#2]
Shows:

/PopPlayground-master/PopPlayground/ViewController.m:46:41: No known class method for selector 'flatRandomColor'

**Comment by victorBaro** [comment]
Hi @bagusflyer 
This is weird... I created a new method in "UIColor+flatColors" category.

Maybe you can try to add it manually.

As you can see here: https://github.com/iBaro/PopPlayground/blob/master/Pods/UIColor%2BFlatColors/UIColor%2BFlatColors/UIColor%2BFlatColors.h
The last method is 'flatRandomColor'.

And here you can find the implementation:
https://github.com/iBaro/PopPlayground/blob/master/Pods/UIColor%2BFlatColors/UIColor%2BFlatColors/UIColor%2BFlatColors.m

**Comment by rhysparry** [comment]
I found this after experiencing the same issue. I had performed a pod install overwriting the flatRandomColor modification. After discarding changes and clean and fresh build worked fine.

**Comment by ruandao** [comment]
get the same issue

**Comment by bartcone** [comment]
@ruandao Don't pod install/update as the new UIColor+FlatColor pod has removed the [UIColor flatRandomColor] method. If you just clone this repo, it will work fine. The pods are included. If you really want to pod install/update, I forked and updated the code to work. https://github.com/bartcone/PopPlayground

**Comment by victorBaro** [comment]
As @bartcone said, the issue is because of flatRandomColor. I am going to pull request this method to flatColors so we don't get that problem any more.

Thank you @bartcone
