### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by hamzazar** [victorBaro/PopPlayground#3]
Hi @iBaro,

I tried to run your project and learn facebook pop animation from it, but I got some errors. I am actually using xcode 6.1. And the project won't run. 

Second for the device can you support also the iphone 4. Because now I see only the ipads simulerator when trying to run the project.

Thanks

**Comment by boyvanamstel** [comment]
Run `pod update` and it'll install a more recent version of pop that works with Xcode 6.1.

**Comment by filipandrei87** [comment]
Yeah... that's not it...
You get a "file not found" error in the .pch file. Seems to be a dependancy error.

**Comment by boyvanamstel** [comment]
My mistake, I thought I was commenting on [another project](https://github.com/callmeed/pop-playground). Regardless, I've created a [pull request](https://github.com/iBaro/PopPlayground/pull/4) that fixes the compile errors in this project.

@hamzazar You can run the app on the iPhone (simulator) by changing the Devices option under the PopPlayground target's general preferences. It will look all messed up though as @iBaro only designed interfaces for the iPad.

**Comment by victorBaro** [comment]
Hello @boyvanamstel 
Thanks a lot for updating the project. Will accept your PR straight away.

Sorry @hamzazar for the building problems. As @boyvanamstel says, I only created an iPad version, I wanted to use it for the screencast purposes only, so this example project will look pretty bad on iPhone screen.

**Comment by hamzazar** [comment]
thanks guys, I will try to run it again.. 

Don't worry @iBaro  for iphone support, just I liked to try it on device because I have only an iphone 4. But no problems I will check the ipad simulator.
